export const ADD_REPO = 'ADD_REPO';
export const ADDING_REPO = 'ADDING_REPO';
export const ADDING_REPO_END = 'ADDING_REPO_END';
export const SHOW_REPO = 'SHOW_REPO';
export const HIDE_REPO = 'HIDE_REPO';
export const DELETE_REPO = 'DELETE_REPO';
export const DELETE_GROUP_CONFIRM = 'DELETE_GROUP_CONFIRM';
export const DELETE_GROUP_CANCEL = 'DELETE_GROUP_CANCEL';
export const UPDATE_REPO = 'UPDATE_REPO';
export const REORDER_REPO = 'REORDER_REPO';
export const RELOADING = 'RELOADING';
export const RELOADING_END = 'RELOADING_END';
export const RELOADING_ALL_REPOS = 'RELOADING_ALL_REPOS';
export const RELOADING_ALL_REPOS_END = 'RELOADING_ALL_REPOS_END';
export const RELOADING_ALL_REPOS_STATUS = 'RELOADING_ALL_REPOS_STATUS';
export const RELOADING_ALL_REPOS_STATUS_END = 'RELOADING_ALL_REPOS_STATUS_END';
export const PULLING = 'PULLING';
export const PULLING_END = 'PULLING_END';

export const ADD_GROUP = 'ADD_GROUP';
export const REORDER_GROUP = 'REORDER_GROUP';
export const DELETE_GROUP = 'DELETE_GROUP';
export const START_EDITING_GROUP = 'START_EDITING_GROUP';
export const EDIT_GROUP = 'EDIT_GROUP';
export const RELOADING_GROUP = 'RELOADING_GROUP';
export const RELOADING_GROUP_END = 'RELOADING_GROUP_END';
export const PULLING_GROUP = 'PULLING_GROUP';
export const PULLING_GROUP_END = 'PULLING_GROUP_END';

export const SHOW_FILE = 'SHOW_FILE';

export const MESSAGE = 'MESSAGE';
// export const DELETE_REPO = 'DELETE_REPO'
// export const EDIT_REPO = 'EDIT_REPO'
// export const COMPLETE_REPO = 'COMPLETE_REPO'
// export const COMPLETE_ALL = 'COMPLETE_ALL'
// export const CLEAR_COMPLETED = 'CLEAR_COMPLETED'
