export const ADD_REPO = 'ADD_REPO';
export const DELETE = 'DELETE';
export const UPDATE = 'UPDATE';
export const RELOADING = 'RELOADING';
export const RELOAD_ALL = 'RELOAD_ALL';
// export const DELETE_REPO = 'DELETE_REPO'
// export const EDIT_REPO = 'EDIT_REPO'
// export const COMPLETE_REPO = 'COMPLETE_REPO'
// export const COMPLETE_ALL = 'COMPLETE_ALL'
// export const CLEAR_COMPLETED = 'CLEAR_COMPLETED'
